# Reserve flow
CHOOSE_ROOM = 0
CHOOSE_DATE = 1
CHOOSE_START_TIME = 2
CHOOSE_END_TIME = 3
CONFIRM = 4

# Cancel reservation flow
CANCEL_CHOOSE = 10

# Admin flows
ADMIN_ROOM_NAME = 20
ADMIN_REMOVE_CHOOSE = 21
